accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
app_name = 'accounts'
urlpatterns = [
    path('signup/',views.signup,name='signup'),
    path('logout/',auth_views.LogoutView.as_view(),name='logout'),
    path('login/',auth_views.LoginView.as_view(template_name='login.html'),name='login'),
    path('settings/change_password/',auth_views.PasswordChangeView.as_view(
        template_name='change_password.html', success_url='done'),name='password_change'),
    path('settings/change_password/done/',auth_views.PasswordChangeDoneView.as_view(
        template_name='change_password_done.html'),name='password_change_done'),
    path('account/',views.UserUpdateView.as_view(),name='my_account')


]

#  path('setting/change_password/', auth_views.PasswordChangeView.as_view(
#     template_name='change_password.html', success_url='done'), name='change_password'),
#     path('setting/change_password/done', auth_views.PasswordChangeDoneView.as_view(
#         template_name='change_password_done.html'), name='change_password_done')

boards/urls.py
from django.urls import path
from . import views
 
app_name = 'boards'
urlpatterns = [
    path('',views.home ,name='home'),
    path('about/',views.about , name='about'),
    path('boards/<int:board_id>/',views.board_topics,name='board_topics'),
    path('boards/<int:board_id>/new/',views.new_topic,name='new_topic'),
    path('boards/<int:board_id>/topics/<int:topic_id>',views.topic_posts,name='topic_posts'),
    path('boards/<int:board_id>/topics/<int:topic_id>/reply/', views.reply_topic, name='reply_topic'),
    path('boards/<int:board_id>/topics/<int:topic_id>/posts/<int:post_id>/edit/',
     views.PostUpdateView.as_view(), name='edit_post'),



] 

desc/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('boards.urls',namespace='boards')),
    path('', include('accounts.urls',namespace = 'accounts')),

]

templates/base.html
{% load static%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{%static 'css/bootstrap.min.css'%}">
    {% block stylesheet %}{% endblock %}

</head>
<body>
{%block body%}
<nav class="navbar navbar-expand-sm navbar-dark bg-dark">
  <div class="container">
    <a class="navbar-brand" href="{% url 'boards:home' %}">Django Boards</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#mainMenu" aria-controls="mainMenu" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="mainMenu">
      {%if user.is_authenticated%}
      <ul class="navbar-nav ml-auto">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="" id="userMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            {{ user.username }}
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userMenu">
            <a class="dropdown-item" href="#">My account</a>
            <a class="dropdown-item" href="{% url 'accounts:password_change' %}">Change password</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{% url 'accounts:logout' %}">Log out</a>
          </div>
        </li>
      </ul>
        {%else%}
        <form class="form-inline ml-auto">
        <a href="{%url 'accounts:login'%}" class="btn btn-outline-secondary">login</a>
        <a href="{%url 'accounts:signup'%}" class="btn btn-primary ml-2">Signup</a>
        </form>
            {%endif%}

    </div>
  </div>
</nav>
<div class="container">
<ol class="breadcrumb my-4">
    {% block breadcrumb %}
    {% endblock %}
</ol>

    {% block content %}
    {% endblock %}

</div>
{%endblock body%}
<script src="{%static 'js/jquery-3.4.1.min.js'%}"></script>
<script src="{%static 'js/popper.min.js'%}"></script>
<script src="{%static 'js/bootstrap.min.js'%}"></script>

</body>
</html>

templates/change_password.html
{% extends 'base.html' %}
{% block title %}Change password{% endblock %}

{% block breadcrumb %}
  <li class="breadcrumb-item active">Change Password</li>
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-lg-6 col-md-8 col-sm-10">
      <form method="post" novalidate>
        {% csrf_token %}
        {% include 'includes/form.html' %}
        <button type="submit" class="btn btn-success">Change password</button>
      </form>
    </div>
  </div>


{% endblock %}

templates/change_password_done.html
{% extends 'base.html' %}
{% block title %}Change password successful{% endblock %}

{% block breadcrumb %}
  <li class="breadcrumb-item "><a href="{%url 'accounts:password_change'%}">Change Password</a> </li>

  <li class="breadcrumb-item active">Success</li>
{% endblock %}

{% block content %}

<div class="alert alert-success" role="alert">
    <strong>Success!</strong> Your password has been changed!
  </div>
  <a href="{% url 'boards:home' %}" class="btn btn-secondary">Return to home page</a>
{% endblock %}

templates/edit_post.html
{% extends 'base.html' %}
{% block title %}Edit Post{% endblock %}

{% block breadcrumb %}
  <li class="breadcrumb-item"><a href="{% url 'boards:home' %}">Boards</a></li>
  <li class="breadcrumb-item"><a href="{% url 'boards:board_topics' post.topic.board.pk %}">{{ post.topic.board.name }}</a></li>
  <li class="breadcrumb-item active">Edit Post</li>
{% endblock %}

{% block content %}
  <form method="post" novalidate class="mb-4">
    {% csrf_token %}
    {% include 'includes/form.html'%}
    <button type="submit" class="btn btn-success">Save changes</button>
  </form>
{% endblock %}

templates/home.html
{% extends 'base.html' %}

{%block title%}Boards {%endblock%}

{% block breadcrumb %}
    <li class="breadcrumb-item active">Boards</li>
{%endblock%}

{% block content %}
<table class="table">
    <thead class="thead-dark">
    <tr>
        <th>Board</th>
        <th>Posts</th>
        <th>Topic</th>
        <th>Last Post</th>
    </tr>
    </thead>
    <tbody>
    {% for board in boards%}
    <tr>
        <td><a href="{% url 'boards:board_topics' board.pk%}">{{board.name}}</a>
            <small class="text-muted d-block">{{board.description}}</small>
            </td>
            <td>{{board.get_posts_count}}</td>
            <td>{{board.topics.count}}</td>
            <td>
                {% with post=board.get_last_post%}
                {%if post%}
                by {{post.created_by.username}} at {{post.created_dt}}
               {%else%}
                <small>No Posts</small>
                {%endif%}
                {%endwith%}
    
            </td>
    </tr>
    {%endfor%}

    </tbody>
</table>

{%endblock%}

templates/login.html
{% extends 'base.html' %}

{% load static %}

{% block stylesheet %}
  <link rel="stylesheet" href="{% static 'css/account.css' %}">
{% endblock %}

{% block body %}
  <div class="container">
    <h1 class="text-center logo my-4">
      <a href="{% url 'boards:home' %}">Django Boards</a>
    </h1>
    <div class="row justify-content-center">
      <div class="col-lg-8 col-md-10 col-sm-12">
        <div class="card">
          <div class="card-body">
            <h3 class="card-title">Log in</h3>
            <form method="post" novalidate>
              {% csrf_token %}
              <input type="hidden" name = "next" value="{{next}}"> 
              {% include 'includes/form.html' %}
              <button type="submit" class="btn btn-primary btn-block">Log in</button>
            </form>
          </div>
          <div class="card-footer text-muted text-center">
            Create New account <a href="{%url 'accounts:signup'%}">Sign up </a>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/my_account.html
{% extends 'base.html' %}

{%block title%}My account {%endblock%}

{% block breadcrumb %}
    <li class="breadcrumb-item active">My account</li>
{%endblock%}

{% block content %}

 <form method="post" novalidate>
    {% csrf_token %}
    {% include 'includes/form.html'%}
    <button type="submit" class="btn btn-success">Save Changes</button>
  </form>
{%endblock%}

templates/new_topic.html
{% extends 'base.html' %}
{% block title %}Start a New Topic{% endblock %}

{% block breadcrumb %}
  <li class="breadcrumb-item"><a href="{% url 'boards:home' %}">Boards</a></li>
  <li class="breadcrumb-item"><a href="{% url 'boards:board_topics' board.pk %}">{{ board.name }}</a></li>
  <li class="breadcrumb-item active">New topic</li>
{% endblock %}

{% block content %}
  <form method="post" novalidate>
    {% csrf_token %}
    {% include 'includes/form.html'%}
    <button type="submit" class="btn btn-success">Add</button>
  </form>
{% endblock %}

templates/reply_topic.html
{% extends 'base.html' %}
{%load static%}
{%block title%}{{topic.subject}} {%endblock%}
{% block breadcrumb %}

   <li class="breadcrumb-item "><a href="{% url 'boards:home' %}">Boards</a></li>
   <li class="breadcrumb-item "><a href="{% url 'boards:board_topics' topic.board.pk %}">{{ topic.board.name}}</a></li>

        <li class="breadcrumb-item active">{{topic.subject}}</li>
        <li class="breadcrumb-item active">Post reply</li>

{%endblock%}


{% block content %}
<form method="post" class="mb-4">
    {%csrf_token%}
    {%include 'includes/form.html'%}
        <button type="submit" class="btn btn-success">Post the reply</button>

</form>

{%for post in topic.posts.all%}
 <div class="col-10">
            <div class="row mb-3">
              <div class="col-6">
                <strong class="text-muted">{{ post.created_by.username }}</strong>
              </div>
              <div class="col-6 text-right">
                <small class="text-muted">{{ post.created_dt }}</small>
              </div>
            </div>
            {{ post.message }}

          </div>

{%endfor%}



{% endblock %}

templates/signup.html
{% extends 'base.html' %}

{% load static %}

{% block stylesheet %}
  <link rel="stylesheet" href="{% static 'css/account.css' %}">
{% endblock %}

{% block body %}
  <div class="container">
    <h1 class="text-center logo my-4">
      <a href="">Django Boards</a>
    </h1>
    <div class="row justify-content-center">
      <div class="col-lg-8 col-md-10 col-sm-12">
        <div class="card">
          <div class="card-body">
            <h3 class="card-title">Sign up</h3>
            <form method="post" novalidate>
              {% csrf_token %}
              {% include 'includes/form.html' %}
              <button type="submit" class="btn btn-primary btn-block">Create an account</button>
            </form>
          </div>
          <div class="card-footer text-muted text-center">
            Already have an account? <a href="{%url 'accounts:login'%}">Log in</a>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/topic_posts.html
{% extends 'base.html' %}
{%load static%}
{%block title%}{{topic.subject}} {%endblock%}
{% block breadcrumb %}

   <li class="breadcrumb-item "><a href="{% url 'boards:home' %}">Boards</a></li>
   <li class="breadcrumb-item "><a href="{% url 'boards:board_topics' topic.board.pk %}">{{ topic.board.name}}</a></li>

        <li class="breadcrumb-item active">{{topic.subject}}</li>
{%endblock%}


{% block content %}
  <div class="mb-4">
    <a href="{% url 'boards:reply_topic' topic.board.pk  topic.pk%}" class="btn btn-primary">Reply</a>
  </div>

    {% for post in topic.posts.all %}
    <div class="card mb-2">
      <div class="card-body p-3">
        <div class="row">
          <div class="col-2">
            <img src="{% static 'img/user.png' %}" alt="{{ post.created_by.username }}" class="w-100">
          </div>
          <div class="col-10">
            <div class="row mb-3">
              <div class="col-6">
                <strong class="text-muted">{{ post.created_by.username }}</strong>
              </div>
              <div class="col-6 text-right">
                <small class="text-muted">{{ post.created_dt }}</small>
              </div>
            </div>
            {{ post.message }}
            {% if post.created_by == user %}
              <div class="mt-3">
                <a href="{% url 'boards:edit_post' post.topic.board.pk post.topic.pk post.pk %}" 
                class="btn btn-primary btn-sm" role="button">Edit</a>
              </div>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  {% endfor %}


{% endblock %}

templates/topics.html
{% extends 'base.html' %}
{%block title%}{{board.name}} {%endblock%}
{% block breadcrumb %}

   <li class="breadcrumb-item "><a href="{% url 'boards:home' %}">Boards</a></li>
        <li class="breadcrumb-item active">{{board.name}}</li>
{%endblock%}


{% block content %}
<div class="mb-4">
    <a href="{% url 'boards:new_topic' board.pk %}" class="btn btn-primary">New topic</a>
</div>

<table class="table">
    <thead class="thead-dark">
    <tr>
        <th>Topic</th>
        <th>Created by</th>
        <th>Posts</th>
        <th>Views</th>
        <th>Created dt</th>
    </tr>
    </thead>
    <tbody>
    {%for topic in topics%}
    <tr>
        <td><a href ="{% url 'boards:topic_posts' board.pk topic.pk %}">{{ topic.subject}}</a></td>
        <td>{{ topic.created_by.username}}</td>
        <td>{{topic.comments}}</td>
        <td>{{topic.views}}</td>
        <td>{{ topic.created_dt}}</td>

    </tr>
    {%endfor%}

    </tbody>
</table>
{% comment %} pagenitor {% endcomment %}
{% if topics.has_other_pages %}
  <nav aria-label="Topics pagination" class="mb-4">
    <ul class="pagination">
      {% if topics.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page={{ topics.previous_page_number }}">Previous</a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <span class="page-link">Previous</span>
        </li>
      {% endif %}

      {% for page_num in topics.paginator.page_range %}
        {% if topics.number == page_num %}
          <li class="page-item active">
            <span class="page-link">
              {{ page_num }}
              <span class="sr-only">(current)</span>
            </span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a>
          </li>
        {% endif %}
      {% endfor %}

      {% if topics.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ topics.next_page_number }}">Next</a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <span class="page-link">Next</span>
        </li>
      {% endif %}
    </ul>
  </nav>
{% endif %}
{% endblock %}